---
version: '3.9'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environement:
      - GF_INSTALL_PLUGIN: marcusolsson-json-datasource
