{
 "title": "Dashboard Velov Lyon (live)",
 "time": { "from": "2022-10-22T22:01:00.000Z", "to": "2022-10-22T22:10:47.000Z" },
 "panels": [
  {
   "title": "Vélos dispo par Stations Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "available_bikes", "type": "timeserie" }
   ]
  },
  {
   "title": "Stands dispos Graphs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "target": "available_bike_stands", "type": "timeserie" }
   ]
  },
  {
   "title": "Tous les vélos dispos",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "target": "all_available_bikes", "type": "timeserie" }
   ]
  },
  {
   "title": "Tous les stands dispo",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "target": "all_bike_stands", "type": "timeserie" }
   ]
  }
 ]
}